// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _03_Infrastructure.Data;

#nullable disable

namespace _03_Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913195345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_04_Domain.Entities.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("_04_Domain.Entities.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdditionalAddressInfo")
                        .HasColumnType("longtext");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AddressNumber")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LegalResponsibleDocument")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LegalResponsibleFullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PublicProfileDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_04_Domain.Entities.Identity.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.AvailableTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AvailableTimeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("AvailableTimes");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.AverageRevenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AverageRevenueName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("AverageRevenues");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.BusinessType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BusinessTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("BusinessTypes");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.ExperienceYears", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExperienceYearsName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ExperienceYears");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.FreelancerOwnMachines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FreelancerId")
                        .HasColumnType("int");

                    b.Property<int>("OwnMachineId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId");

                    b.HasIndex("OwnMachineId");

                    b.ToTable("FreelancerOwnMachines");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.FreelancerPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FreelancerPreferencesName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("FreelancerPreferences");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.FreelancerSpecialties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FreelancerId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FreelancerId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("FreelancerSpecialties");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.HowUsuallyArrangeServices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HowUsuallyArrangeServicesName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("HowUsuallyArrangeServices");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.OwnMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OwnMachineName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("OwnMachines");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SpecialtyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.WorkshopSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkshopSizeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("WorkshopSizes");
                });

            modelBuilder.Entity("_04_Domain.Entities.Profiles.CompanyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyRegistrationDocument")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CoreBusiness")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CompaniesProfiles");
                });

            modelBuilder.Entity("_04_Domain.Entities.Profiles.FreelancerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AvailableTimeId")
                        .HasColumnType("int");

                    b.Property<int>("AverageRevenueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("BusinessTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExperienceYearsId")
                        .HasColumnType("int");

                    b.Property<int>("FreelancerPreferencesId")
                        .HasColumnType("int");

                    b.Property<bool>("HasFixedProducer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasOwnCar")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("HowUsuallyArrangeServicesId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopSizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvailableTimeId");

                    b.HasIndex("AverageRevenueId");

                    b.HasIndex("BusinessTypeId");

                    b.HasIndex("ExperienceYearsId");

                    b.HasIndex("FreelancerPreferencesId");

                    b.HasIndex("HowUsuallyArrangeServicesId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WorkshopSizeId");

                    b.ToTable("FreelancersProfiles");
                });

            modelBuilder.Entity("_04_Domain.Entities.Identity.UserRole", b =>
                {
                    b.HasOne("_04_Domain.Entities.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_04_Domain.Entities.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.FreelancerOwnMachines", b =>
                {
                    b.HasOne("_04_Domain.Entities.Profiles.FreelancerProfile", "Freelancer")
                        .WithMany("FreelancerOwnMachines")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_04_Domain.Entities.ObjectsFields.OwnMachine", "OwnMachine")
                        .WithMany("FreelancerOwnMachines")
                        .HasForeignKey("OwnMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("OwnMachine");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.FreelancerSpecialties", b =>
                {
                    b.HasOne("_04_Domain.Entities.Profiles.FreelancerProfile", "Freelancer")
                        .WithMany("FreelancerSpecialties")
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_04_Domain.Entities.ObjectsFields.Specialty", "Specialty")
                        .WithMany("FreelancerSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("_04_Domain.Entities.Profiles.CompanyProfile", b =>
                {
                    b.HasOne("_04_Domain.Entities.Identity.User", "User")
                        .WithOne("CompanyProfile")
                        .HasForeignKey("_04_Domain.Entities.Profiles.CompanyProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("_04_Domain.Entities.Profiles.FreelancerProfile", b =>
                {
                    b.HasOne("_04_Domain.Entities.ObjectsFields.AvailableTime", "AvailableTime")
                        .WithMany()
                        .HasForeignKey("AvailableTimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_04_Domain.Entities.ObjectsFields.AverageRevenue", "AverageRevenue")
                        .WithMany()
                        .HasForeignKey("AverageRevenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_04_Domain.Entities.ObjectsFields.BusinessType", "BusinessType")
                        .WithMany()
                        .HasForeignKey("BusinessTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_04_Domain.Entities.ObjectsFields.ExperienceYears", "ExperienceYears")
                        .WithMany()
                        .HasForeignKey("ExperienceYearsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_04_Domain.Entities.ObjectsFields.FreelancerPreferences", "FreelancerPreferences")
                        .WithMany()
                        .HasForeignKey("FreelancerPreferencesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_04_Domain.Entities.ObjectsFields.HowUsuallyArrangeServices", "HowUsuallyArrangeServices")
                        .WithMany()
                        .HasForeignKey("HowUsuallyArrangeServicesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_04_Domain.Entities.Identity.User", "User")
                        .WithOne("FreelancerProfile")
                        .HasForeignKey("_04_Domain.Entities.Profiles.FreelancerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_04_Domain.Entities.ObjectsFields.WorkshopSize", "WorkshopSize")
                        .WithMany()
                        .HasForeignKey("WorkshopSizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvailableTime");

                    b.Navigation("AverageRevenue");

                    b.Navigation("BusinessType");

                    b.Navigation("ExperienceYears");

                    b.Navigation("FreelancerPreferences");

                    b.Navigation("HowUsuallyArrangeServices");

                    b.Navigation("User");

                    b.Navigation("WorkshopSize");
                });

            modelBuilder.Entity("_04_Domain.Entities.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("_04_Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("CompanyProfile")
                        .IsRequired();

                    b.Navigation("FreelancerProfile")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.OwnMachine", b =>
                {
                    b.Navigation("FreelancerOwnMachines");
                });

            modelBuilder.Entity("_04_Domain.Entities.ObjectsFields.Specialty", b =>
                {
                    b.Navigation("FreelancerSpecialties");
                });

            modelBuilder.Entity("_04_Domain.Entities.Profiles.FreelancerProfile", b =>
                {
                    b.Navigation("FreelancerOwnMachines");

                    b.Navigation("FreelancerSpecialties");
                });
#pragma warning restore 612, 618
        }
    }
}
